#!/usr/bin/env bash
# Netrange Ultra Pro — Version 2.0
# Author: Vishal ❤️ Subhi
# Features: ASCII Logo, HTML/PDF/CSV/JSON Reporting, Parallel Resolution

set -euo pipefail

# -------------------------
# Colors & Branding
# -------------------------
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
PURPLE='\033[0;35m'
NC='\033[0m'

show_logo() {
  echo -e "${PURPLE}"
  echo "  _   _      _                                     "
  echo " | \ | | ___| |_ _ __ __ _ _ __   __ _  ___       "
  echo " |  \| |/ _ \ __| '__/ _\` | '_ \ / _\` |/ _ \      "
  echo " | |\  |  __/ |_| | | (_| | | | | (_| |  __/      "
  echo " |_| \_|\___|\__|_|  \__,_|_| |_|\__, |\___|      "
  echo "                                 |___/            "
  echo -e "         ${RED}Vishal ❤️  Subhi${PURPLE} Edition${NC}"
  echo "--------------------------------------------------"
}

# -------------------------
# Config & Paths
# -------------------------
INPUT_FILE="${1:-}"
OUTDIR_BASE="netrange_pro_output"
TS=$(date +%Y%m%d_%H%M%S)
OUTDIR="${OUTDIR_BASE}_${TS}"
REPORTS_DIR="$OUTDIR/reports"

if [ -z "$INPUT_FILE" ]; then
  show_logo
  echo -e "${YELLOW}Usage: $0 <input_file>${NC}"
  exit 1
fi

mkdir -p "$REPORTS_DIR"
show_logo

# --- Step 1: Resolve & Process (Using Python for Speed & Logic) ---
echo -e "${GREEN}[*] Processing targets from: $INPUT_FILE${NC}"
RAW_IPS="$OUTDIR/raw_ips.txt"
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" "$INPUT_FILE" > "$RAW_IPS" || true

# --- Step 2: Multi-Format Reporting ---
python3 - <<PY
import ipaddress
import json
import csv
import os
from datetime import datetime

out_dir = "$OUTDIR"
reports_dir = "$REPORTS_DIR"
ips = set()

# Load and validate IPs
try:
    with open("$RAW_IPS", 'r') as f:
        for line in f:
            ip = line.strip()
            if ip:
                try:
                    ipaddress.ip_address(ip)
                    ips.add(ip)
                except: continue
except: pass

# Collapse to CIDR
ip_objs = [ipaddress.ip_network(ip + '/32') for ip in ips]
collapsed = list(ipaddress.collapse_addresses(ip_objs))

# 1. JSON Export
json_data = [{"network": str(n), "hosts": n.num_addresses, "private": n.is_private} for n in collapsed]
with open(os.path.join(reports_dir, "report.json"), 'w') as f:
    json.dump(json_data, f, indent=4)

# 2. CSV Export
with open(os.path.join(reports_dir, "report.csv"), 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(["Network Range", "Total Hosts", "Is Private"])
    for n in collapsed:
        writer.writerow([str(n), n.num_addresses, n.is_private])

# 3. Enhanced HTML Export with Logo Branding
html_file = os.path.join(reports_dir, "report.html")
current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Netrange Pro Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f0f2f5; color: #333; margin: 0; padding: 40px; }}
        .container {{ max-width: 900px; margin: auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }}
        .header {{ text-align: center; border-bottom: 2px solid #eee; margin-bottom: 30px; padding-bottom: 20px; }}
        h1 {{ color: #2d3436; margin-bottom: 5px; }}
        .author {{ color: #e74c3c; font-weight: bold; font-size: 1.2em; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th {{ background-color: #0984e3; color: white; padding: 15px; text-align: left; }}
        td {{ padding: 12px; border-bottom: 1px solid #eee; }}
        tr:hover {{ background-color: #f9f9f9; }}
        .footer {{ text-align: center; margin-top: 40px; font-size: 0.8em; color: #636e72; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Netrange Recon Report</h1>
            <div class="author">Created with ❤️ by Vishal & Subhi</div>
            <p>Scan Date: {current_time}</p>
        </div>
        <table>
            <tr><th>Network Range</th><th>Total Hosts</th><th>Type</th></tr>
            {"".join([f"<tr><td>{n}</td><td>{n.num_addresses}</td><td>{'Private' if n.is_private else 'Public'}</td></tr>" for n in collapsed])}
        </table>
        <div class="footer">
            Generated by Netrange Ultra Pro v2.0
        </div>
    </div>
</body>
</html>
"""
with open(html_file, 'w') as f:
    f.write(html_content)
PY

# --- Step 4: PDF Generation (Optional) ---
if command -v pandoc &> /dev/null; then
    echo -e "${GREEN}[*] Generating PDF Report...${NC}"
    pandoc "$REPORTS_DIR/report.html" -o "$REPORTS_DIR/report.pdf" 2>/dev/null || true
fi

# --- Summary Output ---
echo -e "\n${BLUE}--------------------------------------------------${NC}"
echo -e "${GREEN}SUCCESS! Scan complete.${NC}"
echo -e "Folder: $OUTDIR"
echo -e "Reports available in: ${YELLOW}TXT, CSV, JSON, HTML, PDF${NC}"
echo -e "${PURPLE}Vishal ❤️  Subhi - Stay Secure!${NC}"
echo -e "${BLUE}--------------------------------------------------${NC}"
